---
- name: Check for online hosts
  hosts: all
  gather_facts: False

  tasks:
    - name: Ping for reachability
      command: ping -c3 {{ inventory_hostname }}
      delegate_to: localhost
      register: ping_result
      ignore_errors: true

    - name: Group hosts by online
      group_by: key=reachable
      when: ping_result.rc == 0

- name: Deploy LibreNMS Poller
  hosts: reachable
  gather_facts: True

  tasks:
    import_role:
      name: librenms_poller
