---
# tasks file for librenms_poller
- name: Import vars for Debian-based OS
  import_vars:
    vars: vars/debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Prerequisites for Debian-based OS
  import_tasks:
    - debian.yml
  when: ansible_os_family == 'Debian'

- name: Import vars for CentOS/RedHat-based OS
  import_vars:
    vars: vars/redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Prerequisites for CentOS/RedHat-based OS
  import_tasks:
    - redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Nginx Web Server
  package:
    name: nginx
    state: present
  when: "{{ webserver }} == 'nginx'"

- name: Install Apache Web Server on Debian-based OS
  package:
    name: apache2
    state: present
  when: ("{{ webserver }} == 'apache'") and ansible_os_family == 'Debian'

- name: Install Apache Web Server on CentOS/RedHat-based OS
  package:
    name: httpd
    state: present
  when: ("{{ webserver }} == 'apache'") and ansible_os_family == 'RedHat'

- name: Add Librenms user account
  user:
    name: librenms
    comment: librenms user account
    create_home: True
    home: /opt/librenms
    shell: /bin/bash
    state: present

- name: Download Librenms Repository
  git:
    repo: https://github.com/librenms/librenms.git
    dest: /opt
    clone: True

- name: Chown librenms /opt/librenms
  file:
    path: /opt/librenms
    owner: librenms
    group: librenms
    mode: "771"

- name: Grant librenms ACL permissions to rrd/logs/bootstrap
  ansible.posix.acl:
    path: "{{ item }}"
    entity: librenms
    etype: group
    permissions: rwx
    default: True
    recursive: True
    state: present
  with_items:
    - /opt/librenms/rrd/
    - /opt/librenms/logs/
    - /opt/librenms/bootstrap/cache/
    - /opt/librenms/storage/

- name: Install PHP composer as librenms user
  remote_user: librenms
  become: True
  become_user: "{{ ansible_ssh_user }}"
  become_password: "{{ ansible_ssh_password }}"
  shell: ./scripts/composer_wrapper.php install --no-dev
  ansible_command_timeout: 3600

- name: Set server timezone
  community.general.timezone:
    name: "{{ time_zone }}"

- name: Prepare MariaDB on Core server
  script: scripts/mysql_setup.sh {{ mysql_password }} {{ poller_ip }}
  delegate_to: "{{ core_server_fqdn }}"

- name: Enable lnms command completion - link
  shell: ln -s /opt/librenms/lnms /usr/loca/bin/lnms

- name: Enable lnms command completion - copy file
  copy:
    src: /opt/librenms/misc/lnms-completion.bash
    dst: /etc/bash_completion.d/

- name: Configure SNMPD
  import_tasks:
    - snmpd.yml

- name: Download SNMP Distro
  get_url:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro

- name: Set permissions on snmp distro
  file:
    path: /usr/bin/distro
    mode: u+x,g+x,o+x

- name: Enable and restart snmpd
  ansible.builtin.service:
    name: snmpd
    state: restarted
    enabled: True

- name: Copy Cron Job
  copy:
    src: /opt/librenms/librenms.nonroot.cron
    dst: /opt/cron.d/librenms

- name: Copy logrotate config
  copy:
    src: /opt/librenms/misc/librenms.logrotate
    dst: /etc/logrotate.d/librenms
