---
# tasks file for librenms_poller
- name: Install Prerequisites for Debian-based OS
  import_vars:
    vars: vars/debian.yml
  import_tasks:
    - debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Prerequisites for CentOS/RedHat-based OS
  import_vars:
    vars: vars/redhat.yml
  import_tasks:
    - redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Nginx Web Server
  package:
    name: nginx
    state: present
  when: "{{ webserver }} == 'nginx'"

- name: Install Apache Web Server on Debian-based OS
  package:
    name: apache2
    state: present
  when: ("{{ webserver }} == 'apache'") and ansible_os_family == 'Debian'

- name: Install Apache Web Server on CentOS/RedHat-based OS
  package:
    name: httpd
    state: present
  when: ("{{ webserver }} == 'apache'") and ansible_os_family == 'RedHat'

- name: Add Librenms user account
  user:
    name: librenms
    comment: librenms user account
    create_home: True
    home: /opt/librenms
    shell: /bin/bash
    state: present

- name: Download Librenms Repository
  git:
    repo: https://github.com/librenms/librenms.git
    dest: /opt
    clone: True

- name: Chown librenms /opt/librenms
  file:
    path: /opt/librenms
    owner: librenms
    group: librenms
    mode: "771"

- name: Grant librenms ACL permissions to rrd/logs/bootstrap
  ansible.posix.acl:
    path: "{{ item }}"
    entity: librenms
    etype: group
    permissions: rwx
    default: True
    recursive: True
    state: present
  with_items:
    - /opt/librenms/rrd/
    - /opt/librenms/logs/
    - /opt/librenms/bootstrap/cache/
    - /opt/librenms/storage/

- name: Install PHP composer as librenms user
  remote_user: librenms
  become: True
  become_user: "{{ ansible_ssh_user }}"
  become_password: "{{ ansible_ssh_password }}"
  shell: ./scripts/composer_wrapper.php install --no-dev
  ansible_command_timeout: 3600

- name: Set server timezone
  community.general.timezone:
    name: "{{ time_zone }}"
