---
- name: Copy snmpd.conf
  copy:
    src: /opt/librenms/snmpd.conf.example
    dst: /etc/snmp/snmpd.conf

- name: Set SNMP String
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regex: "RANDOMSTRINGGOESHERE"
    line: "com2sec readonly  default         {{ snmp_string }}"
